# Generated by Django 5.1.6 on 2025-02-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_likes_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
