# Generated by Django 5.1.6 on 2025-03-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
    ]
