# Generated by Django 5.1.6 on 2025-02-20 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_user_otp_email'),
        ('product', '0006_remove_product_likes_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_info',
            new_name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
