# Generated by Django 5.1.6 on 2025-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
