# Generated by Django 5.1.6 on 2025-02-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_user_otp_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.EmailField(max_length=254),
        ),
    ]
